version: '3.8'

services:
  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rifat
      MYSQL_DATABASE: jwt
      MYSQL_USER: rifat
      MYSQL_PASSWORD: rifat
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
